spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true











logging:
  pattern:
    console: '%d - %msg%n'
#  path: /var/log/tomcat 输出的有一个就好了 没有自己设置文件名称 就默认为 spring.log
  file: /var/log/tomcat/sell.log/
#  level:
#    root: debug
#  level: debug 不行
#  level:
server:
  context-path: /sell
#    com.imooc.LoggerTestBetter: debug