spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true











logging:
  pattern:
    console: '%d - %msg%n'
#  path: /var/log/tomcat 输出的有一个就好了 没有自己设置文件名称 就默认为 spring.log
  file: /var/log/tomcat/sell.log/
#  level:
#    root: debug
#  level: debug 不行
#  level:
server:
  context-path: /sell
#    com.imooc.LoggerTestBetter: debug

wechat:
  mpAppId: wxe50e100d05b3827b
  mpAppSecret: f882cb83cced8367542067d71208de03
#  mpAppId: wxd898fcb01713c658
#  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://seeumt.natapp1.cc/sell/pay/notify