spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379









logging:
  pattern:
    console: '%d - %msg%n'
  #  path: /var/log/tomcat 输出的有一个就好了 没有自己设置文件名称 就默认为 spring.log
  file: /var/log/tomcat/sell.log/
#  level:
#    root: debug
#  level: debug 不行
#  level:
#    root: com.imooc.dataobject.mapper：trace 无法打印sql语句

server:
  context-path: /sell
  port: 8090
#    com.imooc.LoggerTestBetter: debug

wechat:
  mpAppId: wxe50e100d05b3827b
  mpAppSecret: f882cb83cced8367542067d71208de03
  openAppId:
  openAppSecret:
  #  mpAppId: wxd898fcb01713c658
  #  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://seeumt.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: gfdjslkfhdsjlkfhldsk还不知道
projectUrl:
  wechatMpAuthorize:  http://seeumt.natapp1.cc
  wechatOpenAuthorize: http://seeumt.natapp1.cc
  sell: http://seeumt.natapp1.cc
mybatis:
  mapper-locations: classpath:mapper/*.xml

aliyunOss:
  endpoint: http://oss-cn-hangzhou.aliyuncs.com
  access-key-id: LTAI4Fr8bs4fisHj6ycb3oxV
  access-key-secret: 1XN63B8wQwq1RPWA0nrxm5YU7YfgDY
  bucket-name: seeumt
  url-prefix: http://seeumt.oss-cn-hangzhou.aliyuncs.com/